[package]
name = "archlinux-autodowngrade"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sudo = "0.6.0"
dialoguer = "0.10.0"
chrono = "0.4.19"